name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential flex libssl-dev libelf-dev python3 zip unzip cpio gcc-aarch64-linux-gnu

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make le7n_defconfig
        make -j$(nproc)

    - name: Upload Image
      uses: actions/upload-artifact@v4
      with:
        name: Image
        path: arch/arm64/boot/Image.gz
